"""
proxy_manager.py - 3proxy Process Manager
Generates 3proxy.cfg from a template, starts/stops the daemon,
and exposes basic runtime statistics.
"""

import os
import signal
import subprocess
import logging
import time
from typing import Optional, Dict, Any

import config

logger = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────────────────────────
# Config template
# ─────────────────────────────────────────────────────────────────────────────

_CFG_TEMPLATE = """\
# 3proxy configuration – generated by XProxy Manager
# Do not edit manually; changes will be overwritten.

daemon
pidfile {pid_file}

# Logging
log {proxy_log} D
logformat "- +_L%t.%.  %N.%p %E %U %C:%c %R:%r %O %I %h %T"

# Authentication
users {username}:CL:{password}

# Allow authenticated users only
auth strong
allow *

# SOCKS5 listener
socks -p{port} -i{bind_ip} -e{bind_ip}
"""


def generate_config(
    port:      int  = config.PROXY_PORT,
    bind_ip:   str  = "0.0.0.0",
    username:  str  = config.PROXY_USER,
    password:  str  = config.PROXY_PASS,
    cfg_path:  str  = config.PROXY_CFG_PATH,
) -> str:
    """
    Write a 3proxy.cfg file and return the rendered contents.

    Raises OSError if the directory cannot be created or the file cannot
    be written.
    """
    os.makedirs(os.path.dirname(cfg_path), exist_ok=True)

    contents = _CFG_TEMPLATE.format(
        pid_file  = config.PID_FILE,
        proxy_log = config.PROXY_LOG_FILE,
        port      = port,
        bind_ip   = bind_ip,
        username  = username,
        password  = password,
    )

    with open(cfg_path, "w") as fh:
        fh.write(contents)

    logger.info("3proxy config written to %s (port=%d user=%s)", cfg_path, port, username)
    return contents


# ─────────────────────────────────────────────────────────────────────────────
# Process helpers
# ─────────────────────────────────────────────────────────────────────────────

def _read_pid() -> Optional[int]:
    """Read the PID from the pid-file; return None if not found or invalid."""
    try:
        with open(config.PID_FILE) as fh:
            return int(fh.read().strip())
    except (FileNotFoundError, ValueError):
        return None


def _pid_alive(pid: int) -> bool:
    """Return True if a process with the given PID is running."""
    try:
        os.kill(pid, 0)  # signal 0 = existence check
        return True
    except (ProcessLookupError, PermissionError):
        return False


def is_running() -> bool:
    """Return True if danted (SOCKS5) is currently running."""
    # Primary: check via systemctl
    try:
        result = subprocess.run(
            ["systemctl", "is-active", "danted"],
            capture_output=True, text=True
        )
        if result.stdout.strip() == "active":
            return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        pass
    # Fallback: check if port 1080 is listening
    try:
        out = subprocess.check_output(
            ["pgrep", "-x", "danted"], stderr=subprocess.DEVNULL
        ).strip()
        return bool(out)
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False


def start_proxy(
    port:     int = config.PROXY_PORT,
    bind_ip:  str = "0.0.0.0",
    username: str = config.PROXY_USER,
    password: str = config.PROXY_PASS,
) -> bool:
    """
    Generate a fresh config then launch 3proxy as a daemon.

    Returns True on success, False on failure.
    """
    if is_running():
        logger.info("start_proxy(): 3proxy already running")
        return True

    try:
        generate_config(port=port, bind_ip=bind_ip, username=username, password=password)
    except OSError as exc:
        logger.error("start_proxy(): config generation failed: %s", exc)
        return False

    if not os.path.isfile(config.PROXY_BIN):
        logger.error("start_proxy(): 3proxy binary not found at %s", config.PROXY_BIN)
        return False

    try:
        proc = subprocess.Popen(
            [config.PROXY_BIN, config.PROXY_CFG_PATH],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            close_fds=True,
        )
        # Give the daemon a moment to write its PID file
        time.sleep(1)
        if is_running():
            logger.info("start_proxy(): 3proxy started (pid=%d)", proc.pid)
            return True
        else:
            logger.error("start_proxy(): 3proxy exited immediately")
            return False
    except OSError as exc:
        logger.error("start_proxy(): failed to exec 3proxy: %s", exc)
        return False


def stop_proxy() -> bool:
    """
    Stop the running 3proxy daemon.

    Tries SIGTERM first, then SIGKILL after 5 seconds.
    Returns True if the process is gone afterwards.
    """
    pid = _read_pid()
    if pid is None:
        # Try pkill as a fallback
        try:
            subprocess.run(["pkill", "-x", "3proxy"], check=False)
        except FileNotFoundError:
            pass
        return not is_running()

    try:
        os.kill(pid, signal.SIGTERM)
        for _ in range(10):
            time.sleep(0.5)
            if not _pid_alive(pid):
                break
        else:
            logger.warning("stop_proxy(): SIGTERM ignored, sending SIGKILL to %d", pid)
            os.kill(pid, signal.SIGKILL)
    except ProcessLookupError:
        pass  # already gone

    # Clean up stale pid file
    try:
        os.remove(config.PID_FILE)
    except FileNotFoundError:
        pass

    alive = is_running()
    if alive:
        logger.error("stop_proxy(): 3proxy is still running after kill attempt")
    else:
        logger.info("stop_proxy(): 3proxy stopped")
    return not alive


def restart_proxy(**kwargs) -> bool:
    """Stop then start 3proxy. kwargs are forwarded to start_proxy()."""
    stop_proxy()
    time.sleep(1)
    return start_proxy(**kwargs)


def get_stats() -> Dict[str, Any]:
    """
    Return runtime statistics for the proxy.

    Attempts to read the 3proxy log file and count connections;
    falls back to zeros if the file does not exist or is unreadable.
    """
    stats: Dict[str, Any] = {
        "running":     is_running(),
        "pid":         _read_pid(),
        "connections": 0,
        "log_lines":   0,
    }

    try:
        with open(config.PROXY_LOG_FILE) as fh:
            lines = fh.readlines()
        stats["log_lines"]   = len(lines)
        # Each log line starting with "- +" is a connection record
        stats["connections"] = sum(1 for l in lines if l.startswith("- +"))
    except (FileNotFoundError, PermissionError):
        pass

    return stats
